In [1]:
import numpy as np

In [3]:
list = [1,2,3,4,5]

In [5]:
a = np.array(list)
a

array([1, 2, 3, 4, 5])

In [9]:
np.arange(1,50,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [21]:
tdarr = np.array([[1,2,3],[4,5,6]])

In [23]:
tdarr.shape

(2, 3)

In [27]:
tdarr.dtype

dtype('int32')

In [33]:
tdarr.ndim

2

In [43]:
farr = np.array(tdarr, ndmin = 3)

In [45]:
farr

array([[[1, 2, 3],
        [4, 5, 6]]])